version: '4'

services:
  chat-with-llms-backend:
    build: ./
    ports:
      - "8080:8080"
    hostname: chat-with-llms-backend
  
  chat-with-llms-frontend:
    build:
      context: ./web
    ports:
      - "3000:3000"
    depends_on:
      - chat-with-llms-backend
    environment:
      - REACT_APP_API_HOST=http://localhost:8080
