version: '3.8'  

services:
  chat-with-llms-backend:
    build: ./
    ports:
      - "8080:8080"
    hostname: chat-with-llms-backend
  
  chat-with-llms-frontend:
    build:
      context: ./web
      args:
        REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID}
        REACT_APP_API_HOST: ${REACT_APP_API_HOST}
    ports:
      - "3000:3000"
    depends_on:
      - chat-with-llms-backend
    environment:
      REACT_APP_GOOGLE_CLIENT_ID: ${REACT_APP_GOOGLE_CLIENT_ID}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}
