import React, {useState} from "react";
import { Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, Button, Slider, Tooltip } from "@nextui-org/react";

export const SettingsModal = ({isOpen, onClose}) => {
  
  const [temperature, setTemperature] = useState(localStorage.getItem("temperature") || 0.7);

  return (
    <>
      <Modal backdrop="blur" isOpen={isOpen} onClose={onClose}>
        <ModalContent>
          {(onClose) => (
            <>
              <ModalHeader className="flex flex-col gap-1">My Settings</ModalHeader>
              <ModalBody>
                <Tooltip content="The numerical value representing the degree of randomness in the responses generated by Large Language Models.">
                <Slider
                  label="Temperature"
                  step={0.01}
                  maxValue={1}
                  minValue={0}
                  defaultValue={0.7}
                  value={temperature}
                  className="max-w-md"
                  onChange={(value) => {
                    setTemperature(value);
                    localStorage.setItem("temperature", value);
                  }}
                />
                </Tooltip>
              </ModalBody>
              <ModalFooter>
                <Button color="danger" variant="light" onPress={onClose}>
                  Close
                </Button>
              </ModalFooter>
            </>
          )}
        </ModalContent>
      </Modal>
    </>
  );
}
