import React, { useState } from "react";
import { Modal, ModalContent, ModalHeader, ModalBody, ModalFooter, Button, Slider, Tooltip, Input } from "@nextui-org/react";

export const SettingsModal = ({ isOpen, onClose }) => {

  const [temperature, setTemperature] = useState(localStorage.getItem("temperature") || 0.7);
  const [history, setHistory] = useState(localStorage.getItem("history") || 10);

  return (
    <>
      <Modal backdrop="blur" isOpen={isOpen} onClose={onClose} isDismissable={false}>
        <ModalContent>
          {(onClose) => (
            <>
              <ModalHeader className="flex flex-col gap-1">My Settings</ModalHeader>
              <ModalBody>
                <Tooltip content="The numerical value representing the degree of randomness in the responses generated by Large Language Models.">
                  <Slider
                    label="Temperature"
                    step={0.01}
                    maxValue={1}
                    minValue={0}
                    defaultValue={0.7}
                    value={temperature}
                    className="max-w-md"
                    onChange={(value) => {
                      setTemperature(value);
                      localStorage.setItem("temperature", value);
                    }}
                  />
                </Tooltip>
                <Input
                  type="number"
                  labelPlacement="outside"
                  label="History"
                  placeholder="10"
                  isInvalid={history < 0 || history > 30}
                  value={history}
                  min={10}
                  max={30}
                  description="The number of previous messages to consider when generating a response. Value must be between 0 and 30."
                  className="max-w-md"
                  onChange={(e) => {
                    if (e.target.value < 0 || e.target.value > 30) return;
                    setHistory(e.target.value);
                    localStorage.setItem("history", e.target.value);
                  }}
                />
              </ModalBody>
              <ModalFooter>
                <Button color="danger" variant="light" onPress={onClose}>
                  Close
                </Button>
              </ModalFooter>
            </>
          )}
        </ModalContent>
      </Modal>
    </>
  );
}
